import groupImage from './groupData';
const matchData = [
        
    {
        h1: "Matchday 1",
        matchday: "matchday1",
        group: "Group A",
        homeFlag: groupImage.germany,
        game: "Germany 5-1 Scotland",
        awayFlag: groupImage.scotland,
        motm: "Musiala",
    },
    {
        matchday: "matchday1",
        group: "Group A",
        homeFlag: groupImage.hungary,
        game: "Hungary 1-3 Switzerland",
        awayFlag: groupImage.switzerland,
        motm: "Xhaka",
    },
    {
        matchday: "matchday1",
        group: "Group B",
        homeFlag: groupImage.spain,
        game: "Spain 3-0 Croatia",
        awayFlag: groupImage.croatia,
        motm: "Ruiz",
    },
    {
        matchday: "matchday1",
        group: "Group B",
        homeFlag: groupImage.italy,
        game: "Italy 2-1 Albania",
        awayFlag: groupImage.albania,
        motm: "Chiesa",
    },
    {
        matchday: "matchday1",
        group: "Group D",
        homeFlag: groupImage.poland,
        game: "Poland 1-2 Netherlands",
        awayFlag: groupImage.netherlands,
        motm: "Gakpo",
    },
    {
        matchday: "matchday1",
        group: "Group C",
        homeFlag: groupImage.slovenia,
        game: "Slovenia 1-1 Denmark",
        awayFlag: groupImage.denmark,
        motm: "Eriksen",
    },
    {
        matchday: "matchday1",
        group: "Group C",
        homeFlag: groupImage.serbia,
        game: "Serbia 0-1 England",
        awayFlag: groupImage.england,
        motm: "Bellingham",
    },
    {
        matchday: "matchday1",
        group: "Group E",
        homeFlag: groupImage.romania,
        game: "Romania 3-0 Ukraine",
        awayFlag: groupImage.ukraine,
        motm: "Stanciu",
    },
    {
        matchday: "matchday1",
        group: "Group E",
        homeFlag: groupImage.belgium,
        game: "Belgium 0-1 Slovakia",
        awayFlag: groupImage.slovakia,
        motm: "Lobotka",
    },
    {
        matchday: "matchday1",
        group: "Group D",
        homeFlag: groupImage.austria,
        game: "Austria 0-1 France",
        awayFlag: groupImage.france,
        motm: "Kante",
    },
    {
        matchday: "matchday1",
        group: "Group F",
        homeFlag: groupImage.turkey,
        game: "Türkiye 3-1 Georgia",
        awayFlag: groupImage.georgia,
        motm: "Guler",
    },
    {
        matchday: "matchday1",
        group: "Group F",
        homeFlag: groupImage.portugal,
        game: "Portugal 2-1 Czechia",
        awayFlag: groupImage.czech,
        motm: "Vitinha",
    },

   
    {
        h1: "Matchday 2",
        matchday: "matchday2",
        group: "Group B",
        homeFlag: groupImage.croatia,
        game: "Croatia 2-2 Albania",
        awayFlag: groupImage.albania,
        motm: "Kramaric",
    },
    {
        matchday: "matchday2",
        group: "Group A",
        homeFlag: groupImage.germany,
        game: "Germany 2-0 Hungary",
        awayFlag: groupImage.hungary,
        motm: "Gundogan",
    },
    {
        matchday: "matchday2",
        group: "Group A",
        homeFlag: groupImage.scotland,
        game: "Scotland 1-1 Switzerland",
        awayFlag: groupImage.switzerland,
        motm: "Akanji",
    },
    {
        matchday: "matchday2",
        group: "Group C",
        homeFlag: groupImage.slovenia,
        game: "Slovenia 1-1 Serbia",
        awayFlag: groupImage.serbia,
        motm: "Karnicnik",
    },
    {
        matchday: "matchday2",
        group: "Group C",
        homeFlag: groupImage.denmark,
        game: "Denmark 1-1 England",
        awayFlag: groupImage.england,
        motm: "Hojbjerg",
    },
    {
        matchday: "matchday2",
        group: "Group B",
        homeFlag: groupImage.spain,
        game: "Spain 1-0 Italy",
        awayFlag: groupImage.italy,
        motm: "Nico Williams",
    },
    {
        matchday: "matchday2",
        group: "Group E",
        homeFlag: groupImage.slovakia,
        game: "Slovakia 1-2 Ukraine",
        awayFlag: groupImage.ukraine,
        motm: "Shaparenko",
    },
    {
        matchday: "matchday2",
        group: "Group D",
        homeFlag: groupImage.poland,
        game: "Poland 1-3 Austria",
        awayFlag: groupImage.austria,
        motm: "Baumgartner",
    },
    {
        matchday: "matchday2",
        group: "Group D",
        homeFlag: groupImage.netherlands,
        game: "Netherlands 0-0 France",
        awayFlag: groupImage.france,
        motm: "Kante",
    },
    {
        matchday: "matchday2",
        group: "Group F",
        homeFlag: groupImage.georgia,
        game: "Georgia 1-1 Czechia",
        awayFlag: groupImage.czech,
        motm: "Mamardashvili",
    },
    {
        matchday: "matchday2",
        group: "Group F",
        homeFlag: groupImage.turkey,
        game: "Türkiye 0-3 Portugal",
        awayFlag: groupImage.portugal,
        motm: "Silva",
    },
    {
        matchday: "matchday2",
        group: "Group E",
        homeFlag: groupImage.belgium,
        game: "Belgium 2-0 Romania",
        awayFlag: groupImage.romania,
        motm: "De Bruyne",
    },
    {
        h1: "Matchday 3",
        matchday: "matchday3",
        group: "Group A",
        homeFlag: groupImage.switzerland,
        game: "Switzerland 1-1 Germany",
        awayFlag: groupImage.germany,
        motm: "Xhaka",
    },
    {
        matchday: "matchday3",
        group: "Group A",
        homeFlag: groupImage.scotland,
        game: "Scotland 0-1 Hungary",
        awayFlag: groupImage.hungary,
        motm: "Sallai",
    },
    {
        matchday: "matchday3",
        group: "Group B",
        homeFlag: groupImage.croatia,
        game: "Croatia 1-1 Italy",
        awayFlag: groupImage.italy,
        motm: "Modric",
    },
    {
        matchday: "matchday3",
        group: "Group B",
        homeFlag: groupImage.albania,
        game: "Albania 0-1 Spain",
        awayFlag: groupImage.spain,
        motm: "Torres",
    },
    {
        matchday: "matchday3",
        group: "Group D",
        homeFlag: groupImage.netherlands,
        game: "Netherlands 2-3 Austria",
        awayFlag: groupImage.austria,
        motm: "Sabitzer",
    },
    {
        matchday: "matchday3",
        group: "Group D",
        homeFlag: groupImage.france,
        game: "France 1-1 Poland",
        awayFlag: groupImage.poland,
        motm: "Lukasz",
    },
    {
        matchday: "matchday3",
        group: "Group C",
        homeFlag: groupImage.england,
        game: "England 0-0 Slovenia",
        awayFlag: groupImage.slovenia,
        motm: "Cerin",
    },
    {
        matchday: "matchday3",
        group: "Group E",
        homeFlag: groupImage.denmark,
        game: "Denmark 0-0 Serbia",
        awayFlag: groupImage.serbia,
        motm: "Eriksen",
    },
    {
        matchday: "matchday3",
        group: "Group E",
        homeFlag: groupImage.slovakia,
        game: "Slovakia 1-1 Romania",
        awayFlag: groupImage.romania,
        motm: "Lobotka",
    },
    {
        matchday: "matchday3",
        group: "Group E",
        homeFlag: groupImage.ukraine,
        game: "Ukraine 0-0 Belgium",
        awayFlag: groupImage.belgium,
        motm: "De bruyne",
    },
    {
        matchday: "matchday3",
        group: "Group F",
        homeFlag: groupImage.czech,
        game: "Czechia 1-2 Turkey",
        awayFlag: groupImage.turkey,
        motm: "Yilmaz",
    },
    {
        matchday: "matchday3",
        group: "Group F",
        homeFlag: groupImage.georgia,
        game: "Georgia 2-0 Portugal",
        awayFlag: groupImage.portugal,
        motm: "Kvaratskhelia",
    },
];

export default matchData