        const button = document.getElementById("button");
        const statsCard = document.getElementById("statsCard");
        const goals = document.getElementById("goals");
        const assists = document.getElementById("assists");
        const yellowCards = document.getElementById("yellow-cards");
        const redCards = document.getElementById("red-cards");
        const position = document.getElementById("position");
        const points = document.getElementById("points");
        const player = document.getElementById("player");
        const playerNameInput = document.getElementById("playerName");
        const nationality = document.getElementById("nationality");
        const players = {  
            mbappe: {
                goals: 1,
                assists: 1,
                dribblesCompleted: 22,
                minutesPlayed: 269,
                position: "attacker",
                points: 12,
                nationalTeam: "France",
            },
            kolomuani:{
                goals: 0,
                assists: 1,
                dribblesCompleted: 2,
                minutesPlayed: 51,
                position: "attacker",
                points: 6,
                nationalTeam: "France",
            },
            thuram: {
                goals: 0,
                assists: 0,
                dribblesCompleted: 7,
                minutesPlayed: 227,
                position: "attacker",
                points: 8,
                nationalTeam: "France",
            },
            dembele: {
                goals: 0,
                assists: 0,
                dribblesCompleted: 22,
                minutesPlayed: 232,
                position: "attacker",
                points: 9,
                nationalTeam: "France",
            },
            griezmann: {
                goals: 0,
                assists: 0,
                dribblesCompleted: 1,
                minutesPlayed: 298,
                position: "attacker",
                points: 7,
                nationalTeam: "France",
            },
            barcola: {
                goals: 0,
                assists: 0,
                dribblesCompleted: 6,
                minutesPlayed: 61,
                position: "attacker",
                points: 3,
                nationalTeam: "France",
            },
            giroud: {
                goals: 0,
                assists: 0,
                dribblesCompleted: 0,
                minutesPlayed: 45,
                position: "attacker",
                points: 3,
                nationalTeam: "France",
            },
            coman: {
                goals: 0,
                assists: 0,
                dribblesCompleted: 0,
                minutesPlayed: 15,
                position: "attacker",
                points: 1,
                nationalTeam: "France",
            },
            tchouameni: {
                ballRecovered: 8,
                assists: 0,
                tackles: 4,
                passes: 241,
                position: "midfielder",
                points: 9,
                nationalTeam: "France",
            },
            kante: {
                ballRecovered: 17,
                assists: 0,
                tackles: 3,
                passes: 198,
                position: "midfielder",
                points: 22,
                nationalTeam: "France",
            },
            rabiot:{
                ballRecovered: 13,
                assists: 0,
                tackles: 2,
                passes: 196,
                position: "midfielder",
                points: 14,
                nationalTeam: "France",
            },
            camavinga: {
                ballRecovered: 3,
                assists: 0,
                tackles: 6,
                passes: 19,
                position: "midfielder",
                points: 3,
                nationalTeam: "France",
            },
            saliba: {
                ballRecovered: 23,
                tackles: 4,
                foulsCommited: 2,
                clearances: 14,
                position: "defender",
                points: 27,
                nationalTeam: "France",
            },
            upamecano: {
                ballRecovered: 25,
                tackles: 7,
                foulsCommited: 2,
                clearances: 14,
                position: "defender",
                points: 26,
                nationalTeam: "France",
            },
            kounde: {
                ballRecovered: 25,
                tackles: 3,
                foulsCommited: 2,
                clearances: 13,
                position: "defender",
                points: 30,
                nationalTeam: "France",
            },
            mendy: {
                ballRecovered: 0,
                tackles: 0,
                foulsCommited: 0,
                clearances: 0,
                position: "defender",
                points: 0,
                nationalTeam: "France",
            },
            hernandez: {
                ballRecovered: 13,
                tackles: 2,
                foulsCommited: 1,
                clearances: 13,
                position: "defender",
                points: 23,
                nationalTeam: "France",
            },
            maignan: {
                    saves: 12,
                    goalsConceded: 1,
                    savesFromPenalty: 0,
                    cleanSheet: 3,
                    position: "goalkeeper",
                    points: 23,
                    nationalTeam: "France",
            },
            ronaldo: {
                goals: 0,
                assists: 1,
                dribblesCompleted: 6,
                minutesPlayed: 366,
                position: "attacker",
                points: 8,
                nationalTeam: "Portugal",
            },
            leao: {
                goals: 0,
                assists: 0,
                dribblesCompleted: 22,
                minutesPlayed: 184,
                position: "attacker",
                points: 4,
                nationalTeam: "Portugal",
            },
            felix: {
                goals: 0,
                assists: 0,
                dribblesCompleted: 7,
                minutesPlayed: 90,
                position: "attacker",
                points: 3,
                nationalTeam: "Portugal",
            },
            jota: {
                goals: 0,
                assists: 0,
                dribblesCompleted: 5,
                minutesPlayed: 97,
                position: "attacker",
                points: 5,
                nationalTeam: "Portugal",
            },
            ramos: {
                goals: 0,
                assists: 0,
                dribblesCompleted: 0,
                minutesPlayed: 24,
                position: "attacker",
                points: 1,
                nationalTeam: "Portugal",
            },
            fernandes: {
                ballRecovered: 10,
                assists: 0,
                tackles: 6,
                passes: 181,
                position: "midfielder",
                points: 15,
                nationalTeam: "Portugal",
            },
            vitinha: {
                ballRecovered: 11,
                assists: 0,
                tackles: 0,
                passes: 196,
                position: "midfielder",
                points: 14,
                nationalTeam: "Portugal",
            },
            silva: {
                ballRecovered: 3,
                assists: 0,
                tackles: 0,
                passes: 155,
                position: "midfielder",
                points: 16,
                nationalTeam: "Portugal",
            },
            pepe: {
                ballRecovered: 30,
                tackles: 2,
                foulsCommited: 1,
                clearances: 13,
                position: "defender",
                points: 23,
                nationalTeam: "Portugal",
            },
            cancelo: {
                ballRecovered: 15,
                tackles: 2,
                foulsCommited: 1,
                clearances: 6,
                position: "defender",
                points: 17,
                nationalTeam: "Portugal",
            },
            dias: {
                ballRecovered: 13,
                tackles: 0,
                foulsCommited: 2,
                clearances: 9,
                position: "defender",
                points: 17,
                nationalTeam: "Portugal",
            },
            mendes: {
                ballRecovered: 17,
                tackles: 10,
                foulsCommited: 3,
                clearances: 8,
                position: "defender",
                points: 22,
                nationalTeam: "Portugal",
            },
            dalot: {
                ballRecovered: 7,
                tackles: 2,
                foulsCommited: 1,
                clearances: 0,
                position: "defender",
                points: 4,
                nationalTeam: "Portugal",
            },
            costa: {
                saves: 6,
                goalsConceded: 3,
                savesFromPenalty: 0,
                cleanSheet: 2,
                position: "goalkeeper",
                points: 19,
                nationalTeam: "Portugal",
            },
         havertz: {
            goals: 2,
            assists: 1,
            dribblesCompleted: 3,
            minutesPlayed: 301,
            position: "attacker",
            points: 19,
            nationalTeam: "Germany",
        },
        sane: {
            goals: 0,
            assists: 0,
            dribblesCompleted: 13,
            minutesPlayed: 161,
            position: "attacker",
            points: 6,
            nationalTeam: "Germany",
        },
        fullkrug: {
            goals: 2,
            assists: 0,
            dribblesCompleted: 0,
            minutesPlayed: 99,
            position: "attacker",
            points: 12,
            nationalTeam: "Germany",
        },
        muller: {
            goals: 0,
            assists: 1,
            dribblesCompleted: 0,
            minutesPlayed: 16,
            position: "attacker",
            points: 4,
            nationalTeam: "Germany",
        },
        musiala: {
            goals: 3,
            assists: 0,
            dribblesCompleted: 28,
            minutesPlayed: 303,
            position: "attacker",
            points: 32,
            nationalTeam: "Germany",
        },
        wirtz: {
            goals: 1,
            assists: 0,
            dribblesCompleted: 6,
            minutesPlayed: 206,
            position: "attacker",
            points: 14,
            nationalTeam: "Germany",
        },
        kroos: {
            ballRecovered: 17,
            assists: 0,
            tackles: 3,
            passes: 416,
            position: "midfielder",
            points: 16,
            nationalTeam: "Germany",
        },
        gundogan: {
            ballRecovered: 5,
            assists: 1,
            tackles: 6,
            passes: 122,
            position: "midfielder",
            points: 24,
            nationalTeam: "Germany",
        },
        andrich: {
            ballRecovered: 13,
            assists: 0,
            tackles: 9,
            passes: 182,
            position: "midfielder",
            points: 11,
            nationalTeam: "Germany",
        },
        rudiger: {
            ballRecovered: 33,
            tackles: 3,
            foulsCommited: 1,
            clearances: 13,
            position: "defender",
            points: 26,
            nationalTeam: "Germany",
        },
        mittelstadt: {
            ballRecovered: 11,
            tackles: 3,
            foulsCommited: 1,
            clearances: 13,
            position: "defender",
            points: 15,
            nationalTeam: "Germany",
        },
        tah: {
            ballRecovered: 14,
            tackles: 3,
            foulsCommited: 1,
            clearances: 13,
            position: "defender",
            points: 12,
            nationalTeam: "Germany",
        },
        kimmich: {
            ballRecovered: 19,
            tackles: 2,
            foulsCommited: 1,
            clearances: 13,
            position: "defender",
            points: 18,
            nationalTeam: "Germany",
        },
        neuer: {
            saves: 7,
            goalsConceded: 2,
            savesFromPenalty: 0,
            cleanSheet: 2,
            position: "goalkeeper",
            points: 17,
            nationalTeam: "Germany",
        },
        // te spanja jom met
        yamal: {
            goals: 0,
            assists: 3,
            dribblesCompleted: 23,
            minutesPlayed: 389,
            position: "attacker",
            points: 23,
            nationalTeam: "Spain",
        },
        williams: {
            goals: 2,
            assists: 2,
            dribblesCompleted: 30,
            minutesPlayed: 394,
            position: "attacker",
            points: 21,
            nationalTeam: "Spain",
        },
        joselu: {
            goals: 0,
            assists: 0,
            dribblesCompleted: 1,
            minutesPlayed: 56,
            position: "attacker",
            points: 7,
            nationalTeam: "Spain",
        },
        morata: {
            goals: 1,
            assists: 2,
            dribblesCompleted: 3,
            minutesPlayed: 267,
            position: "attacker",
            points: 14,
            nationalTeam: "Spain",
        },
        rodri: {
            ballRecovered: 23,
            assists: 1,
            tackles: 15,
            passes: 425,
            position: "midfielder",
            points: 26,
            nationalTeam: "Spain",
        },
        pedri: {
            ballRecovered: 5,
            assists: 2,
            tackles: 4,
            passes: 235,
            position: "midfielder",
            points: 12,
            nationalTeam: "Spain",
        },
        ruiz: {
            ballRecovered: 25,
            assists: 1,
            tackles: 5,
            passes: 312,
            position: "midfielder",
            points: 31,
            nationalTeam: "Spain",
        },
        cucurella: {
            ballRecovered: 24,
            tackles: 2,
            foulsCommited: 5,
            clearances: 15,
            position: "defender",
            points: 18,
            nationalTeam: "Spain",
        },
        carvajal: {
            ballRecovered: 41,
            tackles: 6,
            foulsCommited: 4,
            clearances: 18,
            position: "defender",
            points: 33,
            nationalTeam: "Spain",
        },
        nacho: {
            ballRecovered: 4,
            tackles: 3,
            foulsCommited: 1,
            clearances: 12,
            position: "defender",
            points: 8,
            nationalTeam: "Spain",
        },
        laporte: {
            ballRecovered: 19,
            tackles: 1,
            foulsCommited: 0,
            clearances: 17,
            position: "defender",
            points: 9,
            nationalTeam: "Spain",
        },
        simon: {
            saves: 5,
            goalsConceded: 2,
            savesFromPenalty: 1,
            cleanSheet: 3,
            position: "goalkeeper",
            points: 22,
            nationalTeam: "Spain",
        },
        bellingham: {
            goals: 2,
            assists: 0,
            dribblesCompleted: 12,
            minutesPlayed: 333,
            position: "attacker",
            points: 27,
            nationalTeam: "England",
        },
        kane: {
            goals: 1,
            assists: 0,
            dribblesCompleted: 0,
            minutesPlayed: 316,
            position: "attacker",
            points: 20,
            nationalTeam: "England",
        },
        foden: {
            goals: 0,
            assists: 0,
            dribblesCompleted: 4,
            minutesPlayed: 251,
            position: "attacker",
            points: 15,
            nationalTeam: "England",
        },
        palmer: {
            goals: 0,
            assists: 0,
            dribblesCompleted: 2,
            minutesPlayed: 59,
            position: "attacker",
            points: 3,
            nationalTeam: "England",
        },
        saka: {
            goals: 0,
            assists: 1,
            dribblesCompleted: 7,
            minutesPlayed: 261,
            position: "attacker",
            points: 9,
            nationalTeam: "England",
        },
        mainoo: {
            ballRecovered: 6,
            assists: 0,
            tackles: 2,
            passes: 57,
            position: "midfielder",
            points: 5,
            nationalTeam: "England",
        },
        arnold: {
            ballRecovered: 5,
            assists: 1,
            tackles: 5,
            passes: 94,
            position: "midfielder",
            points: 4,
            nationalTeam: "England",
        },
        gallagher: {
            ballRecovered: 4,
            assists: 0,
            tackles: 2,
            passes: 77,
            position: "midfielder",
            points: 6,
            nationalTeam: "England",
        },
        rice: {
            ballRecovered: 24,
            assists: 0,
            tackles: 5,
            passes: 211,
            position: "midfielder",
            points: 12,
            nationalTeam: "England",
        },
        guehi: {
            ballRecovered: 5,
            tackles: 1,
            foulsCommited: 0,
            clearances: 3,
            position: "defender",
            points: 19,
            nationalTeam: "England",
        },
        walker: {
            ballRecovered: 7,
            tackles: 0,
            foulsCommited: 3,
            clearances: 4,
            position: "defender",
            points: 12,
            nationalTeam: "England",
        },
        stones: {
            ballRecovered: 4,
            tackles: 2,
            foulsCommited: 3,
            clearances: 6,
            position: "defender",
            points: 17,
            nationalTeam: "England",
        },
        trippier: {
            ballRecovered: 3,
            tackles: 0,
            foulsCommited: 3,
            clearances: 15,
            position: "defender",
            points: 11,
            nationalTeam: "England",
        },
        pickford: {
            saves: 2,
            goalsConceded: 2,
            savesFromPenalty: 0,
            cleanSheet: 2,
            position: "goalkeeper",
            points: 19,
            nationalTeam: "England",
        },
        shaqiri: {
            goals: 1,
            assists: 0,
            dribblesCompleted: 0,
            minutesPlayed: 67,
            position: "attacker",
            points: 8,
            nationalTeam: "Switzerland",
        },
        embolo: {
            goals: 1,
            assists: 1,
            dribblesCompleted: 2,
            minutesPlayed: 162,
            position: "attacker",
            points: 12,
            nationalTeam: "Switzerland",
        },
        vargas: {
            ballRecovered: 10,
            assists: 0,
            tackles: 2,
            passes: 151,
            position: "midfielder",
            points: 10,
            nationalTeam: "Switzerland",
        },
        xhaka: {
            ballRecovered: 21,
            assists: 0,
            tackles: 5,
            passes: 319,
            position: "midfielder",
            points: 16,
            nationalTeam: "Switzerland",
        },
        akanji: {
            ballRecovered: 8,
            tackles: 2,
            foulsCommited: 2,
            clearances: 12,
            position: "defender",
            points: 22,
            nationalTeam: "Switzerland",
        },
        sommer: {
            saves: 3,
            goalsConceded: 2,
            savesFromPenalty: 0,
            cleanSheet: 2,
            position: "goalkeeper",
            points: 12,
            nationalTeam: "Switzerland",
        },
        guler: {
            goals: 1,
            assists: 1,
            dribblesCompleted: 12,
            minutesPlayed: 256,
            position: "attacker",
            points: 25,
            nationalTeam: "Turkey",
        },
        baris: {
            goals: 1,
            assists: 0,
            dribblesCompleted: 23,
            minutesPlayed: 301,
            position: "attacker",
            points: 19,
            nationalTeam: "Turkey",
        },
        calhanoglu: {
            ballRecovered: 23,
            assists: 1,
            tackles: 4,
            passes: 222,
            position: "midfielder",
            points: 14,
            nationalTeam: "Switzerland",
        },
        kadioglu: {
            ballRecovered: 24,
            tackles: 6,
            foulsCommited: 1,
            clearances: 2,
            position: "defender",
            points: 25,
            nationalTeam: "Turkey",
        },
        demiral: {
            ballRecovered: 20,
            tackles: 3,
            foulsCommited: 0,
            clearances: 7,
            position: "defender",
            points: 13,
            nationalTeam: "Turkey",
        },
        gunok: {
            saves: 5,
            goalsConceded: 6,
            savesFromPenalty: 0,
            cleanSheet: 0,
            position: "goalkeeper",
            points: 8,
            nationalTeam: "Turkey",
        },
        malen: {
            goals: 2,
            assists: 0,
            dribblesCompleted: 21,
            minutesPlayed: 154,
            position: "attacker",
            points: 16,
            nationalTeam: "Netherlands",
        },
        gakpo: {
            goals: 2,
            assists: 0,
            dribblesCompleted: 5,
            minutesPlayed: 394,
            position: "attacker",
            points: 23,
            nationalTeam: "Netherlands",
        },
        depay: {
            goals: 1,
            assists: 0,
            dribblesCompleted: 12,
            minutesPlayed: 352,
            position: "attacker",
            points: 19,
            nationalTeam: "Netherlands",
        },
        weghorst: {
            goals: 1,
            assists: 0,
            dribblesCompleted: 0,
            minutesPlayed: 98,
            position: "attacker",
            points: 14,
            nationalTeam: "Netherlands",
        },
        veerman: {
            ballRecovered: 5,
            assists: 0,
            tackles: 0,
            passes: 67,
            position: "midfielder",
            points: 4,
            nationalTeam: "Netherlands",
        },
        rejinders: {
            ballRecovered: 6,
            assists: 0,
            tackles: 2,
            passes: 235,
            position: "midfielder",
            points: 6,
            natnationalTeamionTeam: "Netherlands",
        },
        ake: {
            ballRecovered: 9,
            tackles: 3,
            foulsCommited: 4,
            clearances: 10,
            position: "defender",
            points: 18,
            nationalTeam: "Netherlands",
        },
        vandijk: {
            ballRecovered: 17,
            tackles: 1,
            foulsCommited: 2,
            clearances: 15,
            position: "defender",
            points: 16,
            nationalTeam: "Netherlands",
        },
        verbruggen: {
            saves: 6,
            goalsConceded: 3,
            savesFromPenalty: 0,
            cleanSheet: 3,
            position: "goalkeeper",
            points: 14,
            nationalTeam: "Netherlands",
        },
     }

        button.addEventListener("click", () => {
            const playerName = playerNameInput.value.trim();
            if (playerName && players[playerName] && players[playerName].position == "attacker") {
                statsCard.style.display = "block";
                player.textContent = `Player: ${playerName.charAt(0).toUpperCase() + playerName.slice(1).toLowerCase()}⚽`;
                goals.textContent = `⚽Goals: ${players[playerName].goals}`;
                assists.textContent = `🅰️Assists: ${players[playerName].assists}`;
                yellowCards.textContent = `🐾Dribbles Completed: ${players[playerName].dribblesCompleted}`;
                redCards.textContent = `Ⓜ️Minutes played: ${players[playerName].minutesPlayed}`;
                position.textContent = `🅿️Position:  ${players[playerName].position.charAt(0).toUpperCase() + players[playerName].position.slice(1).toLowerCase() }`;
                points.textContent = `⏺️Points: ${players[playerName].points}`;
                nationality.textContent = `🏞️Nationality: ${players[playerName].nationalTeam}`;
            }
            else if(playerName && players[playerName] && players[playerName].position == "midfielder"){
                statsCard.style.display = "block";
                player.textContent = `Player: ${playerName.charAt(0).toUpperCase() + playerName.slice(1).toLowerCase()}💢`;
                goals.textContent = `⚽Ball Recovered: ${players[playerName].ballRecovered}`;
                assists.textContent = `🅰️Assists: ${players[playerName].assists}`;
                yellowCards.textContent = `🦶🏻Tackles: ${players[playerName].tackles}`;
                redCards.textContent = `🤾🏻‍♀️Passes: ${players[playerName].passes}`;
                position.textContent = `🅿️Position: ${players[playerName].position.charAt(0).toUpperCase() + players[playerName].position.slice(1).toLowerCase() }`;
                points.textContent = `⏺️Points: ${players[playerName].points}`;
                nationality.textContent = `🏞️Nationality: ${players[playerName].nationalTeam}`;
            }
            else if(playerName && players[playerName] && players[playerName].position == "defender"){
                statsCard.style.display = "block";
                player.textContent = `Player: ${playerName.charAt(0).toUpperCase() + playerName.slice(1).toLowerCase()}🛡️`;
                goals.textContent = `⚽Ball Recovered: ${players[playerName].ballRecovered}`;
                assists.textContent = `🦶🏻Tackles: ${players[playerName].tackles}`;
                yellowCards.textContent = `🧎🏻‍♂️Fouls Commited : ${players[playerName].foulsCommited}`;
                redCards.textContent = `©️ Clearances: ${players[playerName].clearances}`;
                position.textContent = `🅿️Position: ${players[playerName].position.charAt(0).toUpperCase() + players[playerName].position.slice(1).toLowerCase() }`;
                points.textContent = `⏺️Points: ${players[playerName].points}`;
                nationality.textContent = `🏞️Nationality: ${players[playerName].nationalTeam}`;
            }
            else if(playerName && players[playerName] && players[playerName].position == "goalkeeper"){
                statsCard.style.display = "block";
                player.textContent = `Player: ${playerName.charAt(0).toUpperCase() + playerName.slice(1).toLowerCase()}🧤`;
                goals.textContent = `🛡️Saves: ${players[playerName].saves}`;
                assists.textContent = `🥅Goals Conceded: ${players[playerName].goalsConceded}`;
                yellowCards.textContent = `⭐Saves from Penalties: ${players[playerName].savesFromPenalty}`;
                redCards.textContent = `🧤Clean sheet: ${players[playerName].cleanSheet}`;
                position.textContent = `🅿️Position: ${players[playerName].position.charAt(0).toUpperCase() + players[playerName].position.slice(1).toLowerCase() }`;
                points.textContent = `⏺️Points: ${players[playerName].points}`;
                nationality.textContent = `🏞️Nationality: ${players[playerName].nationalTeam}`;
            }
            
            else {
                statsCard.style.display = "none";
                alert(`Player '${playerName}' not found or no name entered.`);
            }

        });
      